apiVersion: v1
kind: Service
metadata:
  name: producer
  namespace: weather-tweets
spec:
  selector:
    app: kafka-producer
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP