apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-client
  namespace: weather-tweets
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-client
  template:
    metadata:
      labels:
        app: go-client
    spec:
      containers:
      - name: go-client
        image: sergiolarios/go-client:latest
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        env:
          - name: KAFKA_SERVER
            value: "my-cluster-kafka-bootstrap:9092"