// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: tweet.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TweetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Weather       string                 `protobuf:"bytes,3,opt,name=weather,proto3" json:"weather,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TweetRequest) Reset() {
	*x = TweetRequest{}
	mi := &file_tweet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TweetRequest) ProtoMessage() {}

func (x *TweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tweet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TweetRequest.ProtoReflect.Descriptor instead.
func (*TweetRequest) Descriptor() ([]byte, []int) {
	return file_tweet_proto_rawDescGZIP(), []int{0}
}

func (x *TweetRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TweetRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *TweetRequest) GetWeather() string {
	if x != nil {
		return x.Weather
	}
	return ""
}

type TweetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TweetResponse) Reset() {
	*x = TweetResponse{}
	mi := &file_tweet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TweetResponse) ProtoMessage() {}

func (x *TweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tweet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TweetResponse.ProtoReflect.Descriptor instead.
func (*TweetResponse) Descriptor() ([]byte, []int) {
	return file_tweet_proto_rawDescGZIP(), []int{1}
}

func (x *TweetResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_tweet_proto protoreflect.FileDescriptor

const file_tweet_proto_rawDesc = "" +
	"\n" +
	"\vtweet.proto\x12\x05tweet\"d\n" +
	"\fTweetRequest\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x18\n" +
	"\aweather\x18\x03 \x01(\tR\aweather\"'\n" +
	"\rTweetResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2F\n" +
	"\fTweetService\x126\n" +
	"\tSendTweet\x12\x13.tweet.TweetRequest\x1a\x14.tweet.TweetResponseB\x03Z\x01/b\x06proto3"

var (
	file_tweet_proto_rawDescOnce sync.Once
	file_tweet_proto_rawDescData []byte
)

func file_tweet_proto_rawDescGZIP() []byte {
	file_tweet_proto_rawDescOnce.Do(func() {
		file_tweet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tweet_proto_rawDesc), len(file_tweet_proto_rawDesc)))
	})
	return file_tweet_proto_rawDescData
}

var file_tweet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tweet_proto_goTypes = []any{
	(*TweetRequest)(nil),  // 0: tweet.TweetRequest
	(*TweetResponse)(nil), // 1: tweet.TweetResponse
}
var file_tweet_proto_depIdxs = []int32{
	0, // 0: tweet.TweetService.SendTweet:input_type -> tweet.TweetRequest
	1, // 1: tweet.TweetService.SendTweet:output_type -> tweet.TweetResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tweet_proto_init() }
func file_tweet_proto_init() {
	if File_tweet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tweet_proto_rawDesc), len(file_tweet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tweet_proto_goTypes,
		DependencyIndexes: file_tweet_proto_depIdxs,
		MessageInfos:      file_tweet_proto_msgTypes,
	}.Build()
	File_tweet_proto = out.File
	file_tweet_proto_goTypes = nil
	file_tweet_proto_depIdxs = nil
}
